testdoc/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include("user.urls"),name="user")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^login$',Login),
    url(r'^register$',Register,name="register"),
    url(r'^logout$',Logout,name="logout"),
    url(r'^index$',Index,name="index"),
    url(r'^findpwd$',Find_pwd,name="findpwd"),
    url(r'^reset$',Reset,name="reset"),
    url(r'^upload$',file_upload,name="upload"),
    url(r'^show$',file_list),
    url(r'^download/(?P<file_path>.*)/$',file_download),
    url(r'^delete/(?P<id>.*)/$',file_delete),
    url(r'^recycle$',file_recycle),
    url(r'^recover/(?P<id>.*)/$',file_recover),
    url(r'^share/(?P<id>.*)/$',file_share),
    url(r'^all_share$',file_all_share),
    url(r'^me_share$',file_me_share),
    url(r'^share_cacle/(?P<id>.*)/$',file_share_cacle),
    url(r'^person$',person),
    url(r'^reset$',Reset),
    url(r'^one$',one),
    url(r'^two$',two),
    url(r'^three$',three),
    url(r'^four$',four),
    url(r'^five$',five),
    url(r'^serach$',serach)
]

user/models.py
import os
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class UserPro(AbstractUser):
    gender = (
        ("1", "男"),
        ("0", "女")
    )
    sex = models.CharField(
        max_length=32,
        choices=gender,
        default="1",
        verbose_name="性别"
    )
    department = models.CharField(
        max_length=32,
        verbose_name="院系"
    )
    person = models.TextField(
        max_length=1024,
        null=True,
        verbose_name="个人信息"
    )

    def __str__(self):
        return self.username

    class Meta:
        ordering = ["date_joined"]
        verbose_name = "所有用户"
        verbose_name_plural = "用户"


def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    return os.path.join("files", filename)


class files(models.Model):
    selvalue = (
        ('one', '教学资源'),
        ('two', '课程内容'),
        ('three', '学生作业'),
        ('four', '普通文档'),
        ('five', '其他文档'),
    )
    file_owner = models.ForeignKey(
        UserPro,
        on_delete=models.CASCADE,
        verbose_name="文档属主"
    )
    file_name = models.CharField(
        max_length=128,
        verbose_name="文档名称"
    )
    file_file = models.FileField(
        upload_to=user_directory_path,
        verbose_name="文档路径"
    )
    file_classify = models.CharField(
        choices=selvalue,
        default="five",
        max_length=32,
        verbose_name="文档分类"
    )
    file_format = models.CharField(
        null=True,
        max_length=32,
        verbose_name="文档格式"
    )
    file_time = models.DateTimeField(
        auto_now_add=True,
        verbose_name="上传时间"
    )
    file_delete = models.BooleanField(
        default=False,
        verbose_name="文档删除"
    )
    file_share = models.BooleanField(
        default=False,
        verbose_name="文档共享"
    )
    file_downloads = models.IntegerField(
        default=0,
        verbose_name="下载次数"
    )

    def __str__(self):
        return self.file_name

    class Meta:
        ordering = ["file_time"]
        verbose_name = "所有文档"
        verbose_name_plural = "文档"

user/forms.py
from django import forms

class FileUploadForm(forms.Form):
    selvalue = (
        ('one','教 学 资 源'),
        ('two','课 程 内 容'),
        ('three','学 生 作 业'),
        ('four','普 通 文 档'),
        ('five','其 他 文 档'),
    )
    file_name = forms.CharField(label="文档名称", max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    file = forms.FileField(label="文档",widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    file_classify = forms.CharField(label="文档分类",max_length=32,widget=forms.widgets.Select(choices=selvalue))

templates/doc_five.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}其他文档{% endblock %}
{% block css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <style>
        .container, .container-fluid {
            padding-left: 0;
        }

        .right-content {
            top: 64PX;
        }

        .main1 {
            font-size: 24px;

        }

        .main1 a {
            color: #2b669a;
        }

        .main1 a:hover {
            color: red;
        }

        .lastnav {
            position: absolute;
            top: 470px;
            left: 30%;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="right-content" class="right-content">
        <main class="container-fluid">
            <div class="container">
                <h3>其他文档</h3>
                {% if files %}
                    <table class="table table-striped">

                        <tbody>
                        <tr>
                            <td>文件名</td>
                            <td>文件分类</td>
                            <td>文件格式</td>
                            <td>文件大小</td>
                            <td>上传时间</td>
                            <td>上传者</td>
                            <td>下载次数</td>
                            <td>删除</td>
                            <td>共享</td>
                            <td>预览</td>
                            <td>下载</td>
                        </tr>
                        {% for file in files %}
                            <tr>
                                <td>{{ file.file_name }}</td>
                                <td>{{ file.get_file_classify_display }}</td>
                                <td>{{ file.file_format }}</td>
                                <td>{{ file.file_file.size | filesizeformat }}</td>
                                <td>{{ file.file_time }}</td>
                                <td>{{ file.file_owner }}</td>
                            <td>&nbsp;&nbsp;&nbsp;&nbsp;{{ file.file_downloads }}&nbsp;&nbsp;次</td>
                                <td><a class="del" id="{{ file.id }}">删除</a></td>

                                {% if file.file_share %}
                                    <td><a class="qxgx" id="{{ file.id }}">取消共享</a></td>
                                {% else %}
                                    <td><a class="gx" id="{{ file.id }}">共享</a></td>
                                {% endif %}

                                {% if 'jpg' == file.file_format or 'png' == file.file_format or 'gif' == file.file_format %}
                                    <td><a href="{{ file.file_file.url }}">预览</a></td>
                                {% else %}
                                    <td>
                                        <a href="http://ow365.cn/?i=18291&furl=http://www.unstop.top:7713/user/download{{ file.file_file.url }}">预览</a>
                                    </td>
                                {% endif %}

                                <td><a href="/user/download{{ file.file_file.url }}">下载</a></td>
                            </tr>
                        {% endfor %}

                        {#                        分页开始#}
                        <nav aria-label="Page navigation" class="lastnav">
                            <ul class="pagination">
                                <li>
                                    {#                                判断前一页是否存在#}
                                    {% if page.has_previous %}
                                        <a href="/user/five?page={{ page.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                    {% else %}
                                        <a href="/user/five?page=1" aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                    {% endif %}
                                </li>
                                {% for i in page_range %}
                                    <li><a href="/user/five?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}

                                <li>
                                    {% if page.has_next %}
                                        <a href="/user/five?page={{ page.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    {% else %}
                                        <a href="/user/five?page={{ page_count }}" aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                        {#                        分页结束#}

                        </tbody>
                    </table>

                {% else %}
                    <p class="main1">您的系统中暂无&nbsp;&nbsp;其他文档&nbsp;&nbsp;分类文档，可以&nbsp;&nbsp;<a
                            href="/user/upload">点击这里</a>&nbsp;&nbsp;上传文档！</p>
                {% endif %}
            </div>
        </main>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'node_modules/sweetalert.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <script>
        $('body').on('click', '.del', function () {
            var id = parseInt($(this).attr('id'));
            (function del() {
                var msg = "您真的确定要删除吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/delete/' + id + '/'
                } else {
                    return false;
                }
            })()


        });
        $('body').on('click', '.gx', function () {
            var id = parseInt($(this).attr('id'));
            (function gx() {
                var msg = "您确认共享吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/share/' + id + '/'
                } else {
                    return false;
                }
            })()

        });
        $('body').on('click', '.qxgx', function () {
            var id = parseInt($(this).attr('id'));
            (function qxgx() {
                var msg = "您确认取消共享吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/share_cacle/' + id + '/'
                } else {
                    return false;
                }
            })()
        });
    </script>
{% endblock %}

templates/doc_four.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}普通文档{% endblock %}
{% block css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <style>
        .container, .container-fluid {
            padding-left: 0;
        }

        .right-content {
            top: 64PX;
        }

        .main1 {
            font-size: 24px;

        }

        .main1 a {
            color: #2b669a;
        }

        .main1 a:hover {
            color: red;
        }

        .lastnav {
            position: absolute;
            top: 470px;
            left: 30%;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="right-content" class="right-content">
        <main class="container-fluid">
            <div class="container">
                <h3>普通文档</h3>
                {% if files %}
                    <table class="table table-striped">

                        <tbody>
                        <tr>
                            <td>文件名</td>
                            <td>文件分类</td>
                            <td>文件格式</td>
                            <td>文件大小</td>
                            <td>上传时间</td>
                            <td>上传者</td>
                            <td>下载次数</td>
                            <td>删除</td>
                            <td>共享</td>
                            <td>预览</td>
                            <td>下载</td>
                        </tr>
                        {% for file in files %}
                            <tr>
                                <td>{{ file.file_name }}</td>
                                <td>{{ file.get_file_classify_display }}</td>
                                <td>{{ file.file_format }}</td>
                                <td>{{ file.file_file.size | filesizeformat }}</td>
                                <td>{{ file.file_time }}</td>
                                <td>{{ file.file_owner }}</td>
                            <td>&nbsp;&nbsp;&nbsp;&nbsp;{{ file.file_downloads }}&nbsp;&nbsp;次</td>
                                <td><a class="del" id="{{ file.id }}">删除</a></td>
                                {% if file.file_share %}
                                    <td><a class="qxgx" id="{{ file.id }}">取消共享</a></td>
                                {% else %}
                                    <td><a class="gx" id="{{ file.id }}">共享</a></td>
                                {% endif %}
                                {% if 'jpg' == file.file_format or 'png' == file.file_format or 'gif' == file.file_format %}
                                    <td><a href="{{ file.file_file.url }}">预览</a></td>
                                {% else %}
                                    <td>
                                        <a href="http://ow365.cn/?i=18291&furl=http://www.unstop.top:7713/user/download{{ file.file_file.url }}">预览</a>
                                    </td>
                                {% endif %}
                                <td><a href="/user/download{{ file.file_file.url }}">下载</a></td>
                            </tr>
                        {% endfor %}

                        {#                        分页开始#}
                        <nav aria-label="Page navigation" class="lastnav">
                            <ul class="pagination">
                                <li>
                                    {#                                判断前一页是否存在#}
                                    {% if page.has_previous %}
                                        <a href="/user/four?page={{ page.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                    {% else %}
                                        <a href="/user/four?page=1" aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                    {% endif %}
                                </li>
                                {% for i in page_range %}
                                    <li><a href="/user/four?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}

                                <li>
                                    {% if page.has_next %}
                                        <a href="/user/four?page={{ page.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    {% else %}
                                        <a href="/user/four?page={{ page_count }}" aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                        {#                        分页结束#}

                        </tbody>
                    </table>

                {% else %}
                    <p class="main1">您的系统中暂无&nbsp;&nbsp;普通文档&nbsp;&nbsp;分类文档，可以&nbsp;&nbsp;<a
                            href="/user/upload">点击这里</a>&nbsp;&nbsp;上传文档！</p>
                {% endif %}
            </div>
        </main>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'node_modules/sweetalert.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <script>
        $('body').on('click', '.del', function () {
            var id = parseInt($(this).attr('id'));
            (function del() {
                var msg = "您真的确定要删除吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/delete/' + id + '/'
                } else {
                    return false;
                }
            })()


        });
        $('body').on('click', '.gx', function () {
            var id = parseInt($(this).attr('id'));
            (function gx() {
                var msg = "您确认共享吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/share/' + id + '/'
                } else {
                    return false;
                }
            })()

        });
        $('body').on('click', '.qxgx', function () {
            var id = parseInt($(this).attr('id'));
            (function qxgx() {
                var msg = "您确认取消共享吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/share_cacle/' + id + '/'
                } else {
                    return false;
                }
            })()
        });

    </script>
{% endblock %}

templates/doc_three.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}学生作业{% endblock %}
{% block css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <style>
        .container, .container-fluid {
            padding-left: 0;
        }

        .right-content {
            top: 64PX;
        }

        .main1 {
            font-size: 24px;

        }

        .main1 a {
            color: #2b669a;
        }

        .main1 a:hover {
            color: red;
        }

        .lastnav {
            position: absolute;
            top: 470px;
            left: 30%;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="right-content" class="right-content">
        <main class="container-fluid">
            <div class="container">
                <h3>学生作业</h3>
                {% if files %}
                    <table class="table table-striped">

                        <tbody>
                        <tr>
                            <td>文件名</td>
                            <td>文件分类</td>
                            <td>文件格式</td>
                            <td>文件大小</td>
                            <td>上传时间</td>
                            <td>上传者</td>
                            <td>下载次数</td>
                            <td>删除</td>
                            <td>共享</td>
                            <td>预览</td>
                            <td>下载</td>
                        </tr>
                        {% for file in files %}
                            <tr>
                                <td>{{ file.file_name }}</td>
                                <td>{{ file.get_file_classify_display }}</td>
                                <td>{{ file.file_format }}</td>
                                <td>{{ file.file_file.size | filesizeformat }}</td>
                                <td>{{ file.file_time }}</td>
                                <td>{{ file.file_owner }}</td>
                            <td>&nbsp;&nbsp;&nbsp;&nbsp;{{ file.file_downloads }}&nbsp;&nbsp;次</td>
                                <td><a class="del" id="{{ file.id }}">删除</a></td>
                                {% if file.file_share %}
                                    <td><a class="qxgx" id="{{ file.id }}">取消共享</a></td>
                                {% else %}
                                    <td><a class="gx" id="{{ file.id }}">共享</a></td>
                                {% endif %}
                                {% if 'jpg' == file.file_format or 'png' == file.file_format or 'gif' == file.file_format %}
                                    <td><a href="{{ file.file_file.url }}">预览</a></td>
                                {% else %}
                                    <td>
                                        <a href="http://ow365.cn/?i=18291&furl=http://www.unstop.top:7713/user/download{{ file.file_file.url }}">预览</a>
                                    </td>
                                {% endif %}
                                <td><a href="/user/download{{ file.file_file.url }}">下载</a></td>
                            </tr>
                        {% endfor %}

                        {#                        分页开始#}
                        <nav aria-label="Page navigation" class="lastnav">
                            <ul class="pagination">
                                <li>
                                    {#                                判断前一页是否存在#}
                                    {% if page.has_previous %}
                                        <a href="/user/three?page={{ page.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                    {% else %}
                                        <a href="/user/three?page=1" aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                    {% endif %}
                                </li>
                                {% for i in page_range %}
                                    <li><a href="/user/three?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}

                                <li>
                                    {% if page.has_next %}
                                        <a href="/user/three?page={{ page.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    {% else %}
                                        <a href="/user/three?page={{ page_count }}" aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                        {#                        分页结束#}

                        </tbody>
                    </table>

                {% else %}
                    <p class="main1">您的系统中暂无&nbsp;&nbsp;学生作业&nbsp;&nbsp;分类文档，可以&nbsp;&nbsp;<a
                            href="/user/upload">点击这里</a>&nbsp;&nbsp;上传文档！</p>
                {% endif %}
            </div>
        </main>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'node_modules/sweetalert.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <script>
        $('body').on('click', '.del', function () {
            var id = parseInt($(this).attr('id'));
            (function del() {
                var msg = "您真的确定要删除吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/delete/' + id + '/'
                } else {
                    return false;
                }
            })()


        });
        $('body').on('click', '.gx', function () {
            var id = parseInt($(this).attr('id'));
            (function gx() {
                var msg = "您确认共享吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/share/' + id + '/'
                } else {
                    return false;
                }
            })()

        });
        $('body').on('click', '.qxgx', function () {
            var id = parseInt($(this).attr('id'));
            (function qxgx() {
                var msg = "您确认取消共享吗？\n\n请确认！";
                if (confirm(msg) == true) {
                    location.href = '/user/share_cacle/' + id + '/'
                } else {
                    return false;
                }
            })()
        });

    </script>
{% endblock %}

templates/find_pwd.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>忘记密码</title>

    <link rel="stylesheet" href="{% static 'css/common.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/register.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/find_pwd.css' %}"/>

</head>

<body>
<!--顶部-->
<div class="nav">
    <div class="nav cl">
        <div class="nav_z z">
            <p>教学文档管理系统</p>
        </div>
        <div class="nav_y y">
            {% if request.session.is_login %}
                <a href="#">当前在线：{{ request.session.user_name }}</a>
                <span>    </span>
                <a href="/user/logout">退出</a>
            {% else %}
                <a href="/user/login">登录</a>
                <span>    </span>
                <a href="/user/register">注册</a>
            {% endif %}
        </div>
    </div>
</div>
<!--顶部结束-->
<div class="main">
    <p>通过邮箱重置密码</p>
    <form action="/user/findpwd" method="post">
        {#        {% csrf_token %}#}
        {% if message %}
            <div class="alert alert-warning">{{ message }}</div>
        {% endif %}
        <div class="main_input">
            <input type="email" placeholder="请输入您的邮箱" class="phone" name="email"/>
        </div>
        <button type="submit" class="register">提&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;交</button>
    </form>
</div>


</body>
</html>

templates/upload_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}文档上传{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <style>
        .right-content {
            top: 80px;
            width: 900px;
        }

        #id_file_name, #id_file {
            background-color: #fff;
        }

        .container {
            width: 900px;
        }

        .btn-info {
            position: relative;
            top: 20px;
            width: 110px;
        }

        .gn p:nth-of-type(3) {
            margin-top: 30px;

        }

        .gn select {
            width: 94px;
            height: 30px;
            border-radius: 4px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="right-content" class="right-content">
        <main class="container-fluid">
            <div class="container">
                {% if heading %}
                    <h3>{{ heading }}</h3>
                {% endif %}
                <form action="/user/upload" method="post" enctype="multipart/form-data" class="gn">
                    {#  {% csrf_token %}#}
                    {{ form.as_p }}
                    <button class="btn btn-info form-control " type="submit" value="submit">提&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;交</button>
                </form>
            </div>
        </main>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        $('body').on('click', $('.gn select'), function () {
            $('.gn select').css('border', 'rgb(169,169,169) 1px solid')
        })
    </script>
{% endblock %}